#!/usr/bin/env bash
set -euf -o pipefail

npm run licensetest

# shellcheck source=../node_modules/sanctuary-scripts/functions
source "${BASH_SOURCE%/*}/../node_modules/sanctuary-scripts/functions"

branches=$(get min-branch-coverage)

set +f
c8 --check-coverage \
   --branches "$branches" \
   --reporter text \
   --reporter html \
   node --experimental-modules \
        --no-warnings \
        -- ./node_modules/.bin/oletus test/*.test.js
