#!/usr/bin/env bash
set -eufo pipefail

# shellcheck source=../node_modules/sanctuary-scripts/functions
source "${BASH_SOURCE%/*}/../node_modules/sanctuary-scripts/functions"

branches="$(get min-branch-coverage)"

c8 --check-coverage \
   --branches "$branches" \
   --reporter lcov \
   --reporter text \
   oletus

npm run build \
   && node -p "require('assert').deepStrictEqual(
      Object.keys(require('.')),
      ['State', 'StateT', 'compose', 'constant', 'done', 'evalState', 'execState', 'get', 'modify', 'next', 'put', 'run'],
      'Bundled exports do not look correct',
      ); 'Bundled exports look correct';"
